### ISSUE TITLE
docker-compose not documented

### ISSUE THREAD

**Issue by Utopiah** [postalserver/docs#18]
The installation page mentions "In addition to Docker, you'll also need docker-compose." yet examples feature individual `docker run` commands. There is no complete installation example so I'm not sure I understand what is going on here. When I usually setup a service via containers I don't expect anything to be installed on the host. Is the `postal` command a wrapper for docker/podman to manage its containers? Is there a way to do it the "usual" way, namely 1 yml file for all services then start/stop it via docker-compose?

**Comment by willpower232** [comment]
The `postal` command relies on docker-compose and you can see in [the installation repository](https://github.com/postalserver/install) that there is a docker-compose.yml file to manage the main processes.

As part of using Postal, you should run a proxy like nginx or caddy and since you already have docker running, it makes sense to also run the proxy in docker so there is a layer of separation.

If you want to add your proxy to the main docker-compose file then sure but it could make things complicated down the line.
